backend/stock_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),

]

stock/urls.py
from django.urls import path
from . import views
from .decorators import user_required, admin_required

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('watchlist/', views.watchlist, name='watchlist'),
    path('stocks/', views.stocks, name='stocks'),  # Both groups can access
    path('portfolio/', views.portfolio, name='portfolio'),
    path('transactions/', views.transactions, name='transactions'),
    path('reload-stocks/',views.reload_stocks, name='reload_stocks'),
    path('logout/', views.user_logout, name='logout'),
    path('purchase_stock/', views.purchase_stock, name='purchase_stock'),
    path('add_to_watchlist/', views.add_to_watchlist, name='add_to_watchlist'),
    path('remove_from_watchlist/', views.remove_from_watchlist, name='remove_from_watchlist'),
    path('sell/<int:transaction_id>/', views.sell_stock, name='sell-stock'),
    path('update-graph/<int:portfolio_id>/', views.update_graph, name='update_graph'),
    path("payment/", views.payment_view, name="payment_view"),
    path("success/", views.success_page, name="success_page"),
    path('stock/<int:stock_id>/', views.stock_analysis, name='stock_analysis'),  
]

stock_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

]

stock/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from datetime import timedelta


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, username, password, **extra_fields)


# User model
class User(AbstractBaseUser, PermissionsMixin):
    ROLES = [
        ('admin', 'Admin'),
        ('user', 'User'),
    ]

    user_id = models.BigAutoField(primary_key=True)
    email = models.EmailField(unique=True, default='defaultemail@example.com')
    username = models.CharField(max_length=50, unique=True, default='Trader')
    first_name = models.CharField(max_length=50, default='FirstName')
    last_name = models.CharField(max_length=50, default='LastName')
    phone = models.CharField(max_length=15, blank=True, default='000-000-0000')
    role = models.CharField(max_length=5, choices=ROLES, default='user')
    budget = models.DecimalField(max_digits=15, decimal_places=2, default=5000.00)
    created_at = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='static/stock/profile_pictures/', default='static/stock/profile_pictures/profile.jpg')

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)  # Change to BooleanField
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        return True  # Simplify for now

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        return True
  


# Portfolio model
class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    portfolio_id = models.BigAutoField(primary_key=True)
    portfolio_name = models.CharField(max_length=100, default='My Portfolio')
    profit_loss = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)
    created_at = models.DateTimeField(default=timezone.now)
    graphs = models.ImageField(upload_to='static/stock/graphs/', default='static/stock/graphs/graph.jpg')


    def __str__(self):
        return f"{self.portfolio_name} - {self.user.username}"
    
    def get_pnl_data(self):
        start_date = self.created_at
        transactions = self.transaction_set.filter(transaction_date__gte=start_date).order_by('transaction_date')
        pnl = 0
        inv_pnl = 0
        pnl_data = []
        for transaction in transactions:
            if transaction.transaction_type == 'bs':
                pnl -= transaction.total_price  # Loss due to bought-then-sold
                inv_pnl += transaction.total_price
            elif transaction.transaction_type == 'sell':
                pnl += transaction.total_price  # Revenue from the sale
            pnl_entry = {
                'date': transaction.transaction_date.date(),
                'transaction_type': transaction.transaction_type,
                'pnl': pnl,
                'inv_pnl': inv_pnl,
            }

            pnl_data.append(pnl_entry)

        return pnl_data


# Stock model
from django.db import models

class Stock(models.Model):
    symbol = models.CharField(max_length=10, unique=True, default='SYMBL')
    name = models.CharField(max_length=100, default='Default Stock')
    market = models.CharField(max_length=50, default='Unknown Market')
    quantity = models.PositiveIntegerField(default=0)
    current_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    open_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    high_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    low_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    previous_close = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='static/stock/stock_graph/', default='static/stock/stock_graph/default.jpg')


    def __str__(self):
        return f"{self.symbol} - {self.name}"



# Transaction model
class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('buy', 'Buy'),
        ('sell', 'Sell'),
        ('bs', 'bought_then_sold')
    ]
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, default=None)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, default=None)
    transaction_type = models.CharField(max_length=4, choices=TRANSACTION_TYPES, default='buy')
    quantity = models.PositiveIntegerField(default=0)
    price_per_share = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    transaction_date = models.DateTimeField(default=timezone.now)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)


    def __str__(self):
        return f"{self.transaction_type} - {self.stock.name} - {self.quantity}"


# Watchlist model
class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, default=None)
    added_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'stock')

    def __str__(self):
        return f"{self.user.username} - {self.stock.name}"


# Dividend model
class Dividend(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, default=None)
    dividend_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    payout_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"Dividend for {self.stock.name}"


# UserSettings model
class UserSettings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    setting_name = models.CharField(max_length=100, default='Default Setting')
    setting_value = models.CharField(max_length=255, blank=True, null=True, default='Default Value')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.setting_name} - {self.user.username}"

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    stripe_charge_id = models.CharField(max_length=100, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    success = models.BooleanField(default=False)

    def __str__(self):
        return f"Payment {self.id} by {self.user.username} - Success: {self.success}"

stock/forms.py
# forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import AuthenticationForm


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'budget', 'image']

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

templates/stock/home.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Pro Trader X</title>
    <link rel="stylesheet" href="{% static 'stock/css/home.css' %}" type="text/css" media="screen" >
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen" >
</head>
<body style="background-image: url('{% static 'stock/images/bg.jpg' %}');">
    <div class="container">
        <h1 class="home-title">Home</h1>
        <h2 class="your-stocks">Your Stocks</h2>
        <table class="stocks-table" border="1">
            <thead>
                <tr>
                    <th>Sr. no.</th>
                    <th>Name of Stocks</th>
                    <th>No. of stocks Owned</th>
                    <th>Average price per stocks purchased</th>
                    <th>Current price per stocks</th>
                    <th>Profit/Loss</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'stock_analysis' transaction.stock.id %}" class="stock-name">{{ transaction.stock.name }} ({{transaction.stock.symbol}})</a>
                        </td>                        
                        <td>{{ transaction.quantity }}</td>
                        <td>Rs. {{ transaction.price_per_share }}</td>
                        <td>Rs. {{ transaction.current_price }}</td>
                        <td>Rs. {{ transaction.profit_loss_possible|floatformat:2 }}</td>
                        <td>
                            <button class="buy-btn" data-stock-id="{{ transaction.stock.id }}" data-transaction-id="{{ transaction.id }}">Buy more</button>
                            <a href="{% url 'sell-stock' transaction.id %}">
                                <button class="sell-btn" data-stock-id="{{ transaction.stock.id }}" data-transaction-id="{{ transaction.id }}">
                                    Sell
                                </button>
                            </a>                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7">No stocks found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $('.buy-btn').click(function() {
            const stockId = $(this).data('stock-id');
        
            alert(`Buy that stock from here.`);
            setTimeout(function() {
                window.location.href = `/stocks`;  // Replace with actual URL pattern
            }, 500);  
        });

        // Check if URL contains 'sold' parameter
        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.has('sold')) {
            const amount = urlParams.get('amount');
            alert(`Successfully sold stocks for Rs. ${amount}`);
        }

    </script>

</body>
</html>
{% endblock body %}

templates/stock/login.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'stock/css/login.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen">
</head>
<body style="background-image: url('{% static 'stock/images/loginbg.jpg' %}');">

    <div class="container">
        <div class="login-form">
            <h2>Login</h2>
            <form method="POST">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="Enter your username"">

                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="Enter Password">

                <button class="button" type="submit">Login</button>

                {% if messages %}
                    <ul class="error-messages">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </form>
        </div>
        <div class="register">
            <h3 class="h3or">Instead</h3>
            <a class="reg" href="../register/">Register</a>
        </div>
    </div>

</body>
</html>

{% endblock body %}

templates/stock/navbar.html
<div class="navbar">
    {% load static %}
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen" >
    <div class="logo">
        <img src="{% static 'stock/images/logo.jpg' %}" alt="Pro Trader X Logo">
    </div>
    
    <ul class="nav-links">
        <li><a href="/"><img src="{% static 'stock/images/home.jpg' %}" alt="Home Icon"><span>Home</span></a></li>
        <li><a href="/watchlist/"><img src="{% static 'stock/images/watchlist.jpg' %}" alt="Watchlist Icon"><span>Watchlist</span></a></li>
        <li><a href="/stocks/"><img src="{% static 'stock/images/stocks.jpg' %}" alt="Stocks Icon"><span>Stocks</span></a></li>
        <li><a href="/portfolio/"><img src="{% static 'stock/images/portfolio.jpg' %}" alt="Portfolio Icon"><span>Portfolio</span></a></li>
        <li><a href="/profile/"><img src="{% static 'stock/images/profile.jpg' %}" alt="Profile Icon"><span>Profile</span></a></li>
    </ul>

    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="login-btn">Logout</a>
    {% else %}
        <a href="{% url 'login' %}" class="login-btn">Login/Register</a>
    {% endif %}
</div>

{% block body %}{% endblock body %}

templates/stock/payment_form.html
{% extends './navbar.html' %}

{% load static %}

{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <link rel="stylesheet" href="{% static 'stock/css/payment_form.css' %}"> 
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}"> 

    <script src="https://js.stripe.com/v3/"></script>
</head>
<body style="background-image: url('{% static 'stock/images/bg.jpg' %}');">
    <div class="container">
        <h1>Complete Your Payment</h1>
        <form action="{% url 'payment_view' %}" method="POST" id="payment-form">
            {% csrf_token %}
            <label for="amount">Amount:</label>
            <input type="number" name="amount" step="0.01" min="0.50" required>

            <div id="card-element"><!-- Stripe will insert the card element here --></div>
            <button type="submit">Pay</button>
            <div class="error-message" id="card-errors" role="alert"></div>
        </form>
    </div>

    <script>
        var stripe = Stripe("{{ stripe_publishable_key }}");
        var elements = stripe.elements();
        var card = elements.create("card");
        card.mount("#card-element");

        var form = document.getElementById("payment-form");
        form.addEventListener("submit", async function(event) {
            event.preventDefault();
            const { token, error } = await stripe.createToken(card);
            if (error) {
                document.getElementById('card-errors').textContent = error.message;  // Display error message
            } else {
                var hiddenInput = document.createElement("input");
                hiddenInput.setAttribute("type", "hidden");
                hiddenInput.setAttribute("name", "stripeToken");
                hiddenInput.setAttribute("value", token.id);
                form.appendChild(hiddenInput);
                form.submit();
            }
        });
    </script>
</body>
{% endblock %}

templates/stock/portfolio.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio - Pro Trader X</title>
    <link rel="stylesheet" href="{% static 'stock/css/portfolio.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>  <!-- Include jQuery -->
</head>
<body style="background-image: url('{% static 'stock/images/bg.jpg' %}');">

    <section class="container">
        <h2 class="heading">Portfolio</h2>

        <div class="portfolio-section">
            <div class="chart-container">
                <img id="portfolio-graph" src="{% static 'stock/graphs/' %}{{portfolio.portfolio_id}}_pnl_graph.png"  alt="Stock Chart" class="chart-image">
                <button class="reload-button" id="reload-graph">Reload Graph</button>  <!-- Reload Button -->
            </div>

            <div class="summary-container">
                <blockquote class="quote">
                    "The four most expensive words in the English language are this time it’s different."
                    <br>~ Sir John Templeton
                </blockquote>

                <div class="summary-box">
                    <h3>Summary</h3>
                    <p><strong>Username:</strong> {{ user.username }}</p>
                    <p><strong>Member since:</strong> {{ user.created_at|date:"d/m/Y" }}</p>
                    <p><strong>Portfolio ID:</strong> {{ portfolio.portfolio_id }}</p>
                    <p><strong>Profit/Loss:</strong> <span class="profit">{{ total_profit_loss_percentage|floatformat:2 }}%</span></p>
                    <p><strong>Profit/Loss in Rupees:</strong> Rs. {{ total_profit_loss }}</p>
                    <p><strong>Total Investment:</strong> Rs. {{ total_investment }}</p>
                    <p><strong>Transactions history:</strong> <a href="../transactions/">Click here</a></p>
                </div>
            </div>
        </div>
    </section>

    <script>
        $(document).ready(function() {
            $('#reload-graph').click(function() {
                $.ajax({
                    url: "{% url 'update_graph' portfolio.portfolio_id %}",  // Replace with your URL pattern
                    type: 'GET',
                    success: function(data) {
                        // Update the graph image source with a new timestamp to prevent caching
                        $('#portfolio-graph').attr('src', data.graph_url + '?t=' + new Date().getTime());
                    },
                    error: function(xhr, status, error) {
                        console.error("Error reloading graph: " + error);
                    }
                });
            });
        });
    </script>

</body>
</html>

{% endblock body %}

templates/stock/profile.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'stock/css/profile.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen">
    <script>
        function triggerFileInput() {
            document.getElementById('file-input').click();
        }
    </script>
</head>

<body style="background-image: url('{% static 'stock/images/bg.jpg' %}');">

    <div class="profile-container">
        <div class="profile-left">
            <div class="profile-pic-container">
                <img src="{{ user.image.url }}" alt="Profile Picture" class="profile-pic">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" id="file-input" name="image" accept="image/*" hidden onchange="this.form.submit()">
                    <button type="button" class="change-pic-btn" onclick="triggerFileInput()">Change Profile Picture</button>
                </form>
            </div>
            <div class="user-card">
                <p><strong>Username:</strong> {{ user.username }}</p>
                <p><strong>Email:</strong> {{ user.email }}</p>
                <p><strong>Phone:</strong> {{ user.phone }}</p>
            </div>
        </div>

        <div class="profile-right">
            <h2>Profile</h2>
            <div class="profile-details">
                <form method="post">
                    {% csrf_token %}
                    <div class="field">
                        <span>First Name:</span>
                        <input type="text" name="first_name" value="{{ user.first_name }}">
                        <button type="submit" class="change-btn">Change</button>
                    </div>
                    <div class="field">
                        <span>Last Name:</span>
                        <input type="text" name="last_name" value="{{ user.last_name }}">
                        <button type="submit" class="change-btn">Change</button>
                    </div>
                    <div class="field">
                        <span>Password:</span>
                        <input type="password" name="password" placeholder="New Password">
                        <button type="submit" class="change-btn">Change</button>
                    </div>
                </form>
                <form method="post">
                    {% csrf_token %}
                    <div class="field">
                        <span>Wallet:</span>
                        <input type="number" name="wallet" value="{{ user.budget }}" step="10">
                        <button type="submit" class="change-btn">Change</button>
                    </div>
                </form>
                <div class="field-user-since">
                    <span>User since:</span>
                    <span class="value">{{ user.created_at|date:"F j, Y" }}</span>
                </div>
            </div>
            <button class="save-changes-btn">Save Changes</button>
        </div>
    </div>

</body>
</html>

{% endblock body %}

templates/stock/register.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'stock/css/register.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen">
</head>
<body style="background-image: url('{% static 'stock/images/loginbg.jpg' %}');">
    <div class="container">
        <div class="register-form">
            <h2>Register</h2>
            <form method="POST" action="{% url 'register' %}">
                {% csrf_token %}
                
                <label for="first-name">First Name:</label>
                <input type="text" id="first-name" name="first-name" placeholder="Enter your first name" required>

                <label for="last-name">Last Name:</label>
                <input type="text" id="last-name" name="last-name" placeholder="Enter your last name" required>

                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="Choose a username" required>

                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="Enter your password" required>
                
                <label for="password-confirm">Confirm Password:</label>
                <input type="password" id="password-confirm" name="password-confirm" required>

                <label for="phone">Phone No.:</label>
                <input type="text" id="phone" name="phone" placeholder="Enter your phone number" required>

                <label for="email">Email-ID:</label>
                <input type="email" id="email" name="email" placeholder="Enter your email" required>

                <button type="submit">Register</button>
            </form>
        </div>
    </div>
</body>
</html>

{% endblock %}

templates/stock/success_page.html
{% extends './navbar.html' %}

{% load static %}

{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Successful</title>
    <link rel="stylesheet" href="{% static 'stock/css/success_page.css' %}"> <!-- Link to the external CSS file -->
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}"> <!-- Link to the external CSS file -->
</head>

<body style="background-image: url('{% static 'stock/images/bg.jpg' %}');">
    <div class="container">
        <h1>Payment Successful!</h1>
        <p>Thank you for your payment. Your transaction has been processed successfully.</p>
        
        <div class="success-details">
            <h2>Transaction Details:</h2>
            <p><strong>Transaction ID:</strong> {{ transaction_id }}</p>
            <p><strong>Amount:</strong> ${{ amount }}</p>
            <p><strong>Date:</strong> {{ date }}</p>
        </div>

        <a href="{% url 'home' %}" class="btn">Return to Home</a>
    </div>
</body>
{% endblock %}

templates/stock/transactions.html
{% extends './navbar.html' %}
{% load static %}

{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction History</title>
    <link rel="stylesheet" href="{% static 'stock/css/navbar.css' %}" type="text/css" media="screen" >
    <link rel="stylesheet" href="{% static 'stock/css/transactions.css' %}" type="text/css" media="screen" >
</head>

<body style="background-image: url('{% static 'stock/images/bg.jpg' %}'); background-repeat: repeat; background-size: auto;">

    
    <div class="table-container">
        <h2 class="table-title">Transaction History</h2>
        <table class="transaction-table">
            <thead>
                <tr>
                    <th>Sr. no.</th>
                    <th>Transaction ID</th>
                    <th>Stocks' name</th>
                    <th>Transaction Type <br> (buy or sell)</th>
                    <th>Average price per stock</th>
                    <th>No. of stocks bought or sold</th>
                    <th>Time of Transaction</th>
                    <th>Total price paid/received</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.stock.name }}</td>
                    <td>{{ transaction.get_transaction_type_display }}</td>
                    <td>Rs. {{ transaction.price_per_share }}</td>
                    <td>{{ transaction.quantity }}</td>
                    <td>{{ transaction.transaction_date|date:"Y-m-d H:i A" }}</td>
                    <td>Rs. {{ transaction.total_price }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8">No transactions found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</body>
</html>

{% endblock body %}